default: &default
  adapter: redis
  url: <%= ENV.fetch('REDIS_URL', 'redis://redis:6379') %>
  password: <%= ENV.fetch('REDIS_PASSWORD', nil).presence %>
  channel_prefix: <%= "task_#{Rails.env}_action_cable" %>

development:
  <<: *default

test:
  adapter: test
  channel_prefix: <%= "task_#{Rails.env}_action_cable"  %>

staging:
  <<: *default

production:
  <<: *default
